networks:
  inception-network:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:custom
    build: requirements/mariadb/.
    init: true
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception-network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PASS_ROOT=${DB_PASS_ROOT}
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    image: wordpress:custom
    build: requirements/wordpress/.
    init: true
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception-network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_URL=${WP_URL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - WP_ROLE=${WP_ROLE}
      - WP_FULL_URL=${WP_FULL_URL}
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:custom
    build:
      context: requirements/nginx/.
      args:
        CERT_FOLDER: ${CERT_FOLDER}
        CERTIFICATE: ${CERTIFICATE}
        KEY: ${KEY}
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    init: true
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception-network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: on-failure

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/marboccu/data/database # su docker /var/lib/mysql/
      o: bind
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /Users/marboccu/data/wordpress_files # su docker /var/www/inception/
      o: bind
